// Public, fixed IDs. Generated by generate-adapter-ids.py.
use pinocchio::Address;
// 11111111111111111111111111111111
pub const SYSTEM: Address = Address::new_from_array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
// TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
pub const TOKEN: Address = Address::new_from_array([6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169]);
// TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
pub const TOKEN2022: Address = Address::new_from_array([6, 221, 246, 225, 238, 117, 143, 222, 24, 66, 93, 188, 228, 108, 205, 218, 182, 26, 252, 77, 131, 185, 13, 39, 254, 189, 249, 40, 216, 161, 139, 252]);
// ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
pub const ASSOCIATED: Address = Address::new_from_array([140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19, 153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89]);
// MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr
pub const MEMO: Address = Address::new_from_array([5, 74, 83, 90, 153, 41, 33, 6, 77, 36, 232, 113, 96, 218, 56, 124, 124, 53, 181, 221, 188, 146, 187, 129, 228, 31, 168, 64, 65, 5, 68, 141]);
// So11111111111111111111111111111111111111112
pub const WSOL: Address = Address::new_from_array([6, 155, 136, 87, 254, 171, 129, 132, 251, 104, 127, 99, 70, 24, 192, 53, 218, 196, 57, 220, 26, 235, 59, 85, 152, 160, 240, 0, 0, 0, 0, 1]);
// CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C
pub const CPMM: Address = Address::new_from_array([169, 42, 90, 139, 79, 41, 89, 82, 132, 37, 80, 170, 147, 253, 91, 149, 181, 172, 230, 168, 235, 146, 12, 147, 148, 46, 67, 105, 12, 32, 236, 115]);
// LockrWmn6K5twhz3y9w1dQERbmgSaRkfnTeTKbpofwE
pub const LOCK: Address = Address::new_from_array([5, 18, 190, 171, 44, 232, 223, 74, 228, 223, 62, 241, 201, 145, 37, 113, 91, 164, 37, 151, 9, 37, 235, 181, 220, 6, 46, 111, 211, 75, 182, 129]);
// 3f7GcQFG397GAaEnv51zR6tsTVihYRydnydDD1cXekxH
pub const LOCK_AUTH: Address = Address::new_from_array([39, 122, 136, 123, 244, 116, 41, 12, 97, 18, 154, 107, 170, 220, 105, 151, 152, 194, 98, 130, 145, 201, 38, 210, 67, 54, 36, 217, 167, 154, 96, 26]);
// Aew8XrvYLkm8B22iRsxbKxZ1rEaT7maYn3tNJNTTN7ft
pub const TREASURY: Address = Address::new_from_array([143, 112, 224, 137, 239, 35, 12, 85, 191, 140, 71, 71, 122, 108, 253, 188, 58, 145, 213, 8, 129, 161, 108, 69, 87, 36, 109, 188, 151, 227, 187, 143]);
// metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
pub const METADATA: Address = Address::new_from_array([11, 112, 101, 177, 227, 209, 124, 69, 56, 157, 82, 127, 107, 4, 195, 205, 88, 184, 108, 115, 26, 160, 253, 181, 73, 182, 209, 188, 3, 248, 41, 70]);
// SysvarRent111111111111111111111111111111111
pub const RENT: Address = Address::new_from_array([6, 167, 213, 23, 25, 44, 92, 81, 33, 140, 201, 76, 61, 74, 241, 127, 88, 218, 238, 8, 155, 161, 253, 68, 227, 219, 217, 138, 0, 0, 0, 0]);
// G95xxie3XbkCqtE39GgQ9Ggc7xBC8Uceve7HFDEFApkc
pub const RAY_CONFIG: Address = Address::new_from_array([224, 241, 144, 106, 195, 93, 122, 255, 158, 189, 180, 199, 111, 117, 84, 251, 220, 77, 79, 219, 249, 191, 168, 218, 64, 189, 27, 73, 28, 93, 228, 229]);
// DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8
pub const RAY_CREATE_FEE: Address = Address::new_from_array([183, 208, 34, 82, 84, 172, 7, 227, 178, 189, 63, 134, 193, 240, 241, 16, 63, 192, 112, 140, 193, 90, 239, 20, 7, 58, 166, 69, 63, 85, 234, 105]);
